[package]
name = "niketsu"
version = "0.1.0"
edition = "2021"
authors = ["Sven Friedrich <sven@autumnal.de>"]
license = "Apache-2.0"

[dependencies]
anyhow = "1"
strum = { version = "0.24", features = ["derive"] }
# clap = { version = "4", features = [ "derive" ] }
log = "0.4"
arc-swap = "1.6"
pretty_env_logger = "0.5"
iced = { version = "0.9", features = ["tokio"] }
iced_native = { version = "0.10" }
tokio = { version = "1.27", features = [ "full" ]}
tokio-native-tls = "0.3"
futures = "0.3"
num-traits = "0.2"
num-derive = "0.3"
thiserror = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_with = "3.0"
serde_json = "1.0"
async-recursion = "1.0"
async-tungstenite = { version = "0.22", features = [ "tokio-runtime", "tokio-native-tls" ] }
serde_millis = "0.1"
directories = "5.0"
dashmap = "5"
url = "2.3"
toml = "0.7"
palette = "0.7"
once_cell = "1.17"
chrono = "0.4"
atomic-counter = "1.0"
elsa = "1.8"
crossbeam-channel = "0.5"
enum_dispatch = "0.3"
getset = "0.1"
whoami = "1.4"

[build-dependencies]
# clap_complete = "4"
# clap = { version = "4", features = [ "derive" ] }
strum = { version = "0.24", features = ["derive"] }
bindgen = "0.65"
