[package]
name = "niketsu"
version = "0.1.0"
edition = "2021"
authors = ["Sven Friedrich <sven@autumnal.de>"]
license = "Apache-2.0"

[dependencies]
niketsu-core.path = "core"
niketsu-mpv.path = "player/mpv"
niketsu-communicator.path = "communicator"
niketsu-iced.path = "ui/iced"
niketsu-ratatui.path = "ui/ratatui"
anyhow.workspace = true
tokio.workspace = true
strum.workspace = true
pretty_env_logger = "0.5"
whoami = "1.4"
clap = { version = "4.4.2", features = ["derive"] }

[build-dependencies]
anyhow.workspace = true
strum.workspace = true
clap_complete = "4"
clap = { version = "4", features = [ "derive" ] }

[dev-dependencies]
log.workspace = true
chrono = "0.4"

[[example]]
name = "ratatui"
