[package]
name = "niketsu"
version = "0.1.0"
edition = "2021"
authors = ["Sven Friedrich <sven@autumnal.de>"]
license = "Apache-2.0"

[dependencies]
anyhow = "1"
strum = { version = "0.25", features = ["derive"] }
ordered-float = "3.9"
clap = { version = "4", features = [ "derive" ] }
typed-builder = "0.16"
rayon = "1.7"
fuzzy-matcher = "0.3"
im = { version = "15.1", features = ["serde", "rayon"] }
arcstr = { version = "1.1", features = ["serde"] }
itertools = "0.11"
fake = "2.8"
log = "0.4"
arc-swap = "1.6"
pretty_env_logger = "0.5"
iced = { version = "0.10", features = ["tokio", "advanced"] }
iced_futures = { version = "0.7" }
tokio = { version = "1.27", features = [ "full" ]}
tokio-native-tls = "0.3"
futures = "0.3"
num-traits = "0.2"
num-derive = "0.4"
thiserror = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_with = "3.0"
serde_json = "1.0"
async-recursion = "1.0"
async-tungstenite = { version = "0.23", features = [ "tokio-runtime", "tokio-native-tls" ] }
serde_millis = "0.1"
directories = "5.0"
tempfile = "3.6"
dashmap = "5"
url = "2.3"
toml = "0.8"
palette = "0.7"
once_cell = "1.17"
chrono = "0.4"
elsa = "1.8"
crossbeam-channel = "0.5"
enum_dispatch = "0.3"
getset = "0.1"
whoami = "1.4"
async-trait = "0.1"
dyn-clone = "1.0"

[build-dependencies]
anyhow = "1"
clap_complete = "4"
clap = { version = "4", features = [ "derive" ] }
strum = { version = "0.25", features = ["derive"] }
bindgen = "0.68"

[[example]]
name = "ratatui"

[[example]]
name = "tauri"
