[package]
name = "niketsu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2"
pest_derive = "2"
anyhow = "1"
strum = { version = "0.24", features = ["derive"] }
clap = { version = "4", features = [ "derive" ] }
log = "0.4"
arc-swap = "1.6"
pretty_env_logger = "0.4"
iced = { version = "0.9", features = [ "tokio"] }
iced_native = "0.10"
tokio = { version = "1.27", features = [ "full", "rt-multi-thread" ]}
futures = "0.3"
num-traits = "0.2"
num-derive = "0.3"
thiserror = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
async-recursion = "1.0"
uuid = { version = "1.3", features = [ "v4", "fast-rng"] }
async-tungstenite = { version = "0.20", features = [ "tokio-runtime" ] }
serde_millis = "0.1"
atomic-counter = "1.0"
directories = "5.0"
dashmap = "5"

[build-dependencies]
clap_complete = "4"
clap = { version = "4", features = [ "derive" ] }
strum = { version = "0.24", features = ["derive"] }
cc = "1.0"
bindgen = "0.64"
