FROM golang:1.20-alpine
WORKDIR /niketsu-server
COPY server/ ./server
COPY LICENSE .
COPY go.mod .
COPY go.sum .

RUN go build -o /bin/niketsu-server server/main.go

ARG CERT=""
ARG DBPATH=".db"
ARG DBSTATINTERVAL=120
ARG DBUPDATEINTERVAL=2
ARG DBWAITTIMEOUT=4
ARG DEBUG=false
ARG HOST="0.0.0.0"
ARG KEY=""
ARG PASSWORD=""
ARG PORT=7766

ENV CERT=${CERT}
ENV DBPATH=${DBPATH}
ENV DBSTATINTERVAL=${DBSTATINTERVAL}
ENV DBUPDATEINTERVAL=${DBUPDATEINTERVAL}
ENV DBWAITTIMEOUT=${DBWAITTIMEOUT}
ENV DEBUG=${DEBUG}
ENV HOST=${HOST}
ENV KEY=${KEY}
ENV PASSWORD=${PASSWORD}
ENV PORT=${PORT}

ENTRYPOINT ["/bin/niketsu-server"]
