[package]
name = "niketsu-communicator"
version = "0.1.0"
edition = "2021"

[dependencies]
niketsu-core.path = "../core"
anyhow.workspace = true
arcstr.workspace = true
log.workspace = true
tokio.workspace = true
serde.workspace = true
im.workspace = true
serde_json = "1.0"
async-tungstenite = { version = "0.24", features = [ "tokio-runtime", "tokio-native-tls" ] }
serde_millis = "0.1"
ordered-float = "4"
tokio-native-tls = "0.3"
futures = "0.3"
async-trait = "0.1"
