use std::collections::HashMap;
use std::task::{Context, Poll};

use either::Either;
use libp2p::PeerId;
use libp2p::core::transport::PortUse;
use libp2p::core::{Endpoint, Multiaddr};
use libp2p::multiaddr::Protocol;
use libp2p::swarm::behaviour::{ConnectionClosed, ConnectionEstablished};
use libp2p::swarm::{
    ConnectionDenied, ConnectionId, FromSwarm, NetworkBehaviour, THandlerInEvent, THandlerOutEvent,
    ToSwarm, dummy,
};
use tracing::debug;

/// Wraps a [`NetworkBehaviour`] so its protocols only ever run over *direct*
/// connections, never over relayed ones (`…/p2p-circuit/…`).
///
/// Like [`super::host_relay::GatedRelayBehaviour`], gating works by handing out
/// a [`dummy::ConnectionHandler`] (which speaks no protocols) instead of the
/// real handler. The decision is made per connection at setup time, based purely
/// on whether the connection's address contains a [`Protocol::P2pCircuit`] — so
/// the inner behaviour can never open a substream over a relay circuit. Relayed
/// connections stay reserved for what hole punching needs (identify, DCUtR,
/// ping), which live in a separate, un-wrapped behaviour.
///
/// `ToSwarm` is left untouched (`= T::ToSwarm`), so the events generated by a
/// `#[derive(NetworkBehaviour)]` inner type — and the dispatch built on top of
/// them — are unaffected by the wrapper.
///
/// Connections that get the dummy handler are tracked in `dummy_connections` so
/// [`on_swarm_event`](NetworkBehaviour::on_swarm_event) can withhold the matching
/// per-connection `FromSwarm` events from `inner`. Without this, `inner` would see
/// `ConnectionClosed` for a connection it never saw `handle_established_*_connection`
/// (and thus no `ConnectionEstablished` bookkeeping) for — several libp2p behaviours
/// (e.g. request-response) assert on that pairing and panic.
///
/// Withholding events is not enough on its own: the `other_established` /
/// `remaining_established` counts inside the *forwarded* events are computed by
/// the swarm across **all** connections to a peer, including the relayed ones
/// hidden from `inner`. Behaviours use those counts to detect a peer's first
/// connection and last disconnection (gossipsub only sends its subscription
/// handshake when `other_established == 0`; gossipsub and kademlia only run
/// full peer cleanup when `remaining_established == 0`; request-response
/// `debug_assert`s its own bookkeeping against them). So before forwarding,
/// the counts are reduced by the number of currently-open dummy connections to
/// that peer, making them consistent with what `inner` has actually seen.
pub(crate) struct DirectOnly<T> {
    inner: T,
    dummy_connections: HashMap<ConnectionId, PeerId>,
}

impl<T> DirectOnly<T> {
    pub(crate) fn new(inner: T) -> Self {
        Self {
            inner,
            dummy_connections: HashMap::new(),
        }
    }

    pub(crate) fn inner_mut(&mut self) -> &mut T {
        &mut self.inner
    }

    /// Currently-open dummy (relayed) connections to `peer`: counted in the
    /// swarm-global connection counts, but invisible to `inner`.
    fn open_dummy_connections_to(&self, peer: PeerId) -> usize {
        self.dummy_connections
            .values()
            .filter(|p| **p == peer)
            .count()
    }
}

/// Mirrors [`libp2p::core::ConnectedPoint::is_relayed`]: a connection is relayed
/// iff its address goes through a circuit relay.
fn addr_is_relayed(addr: &Multiaddr) -> bool {
    addr.iter().any(|p| p == Protocol::P2pCircuit)
}

impl<T: NetworkBehaviour> NetworkBehaviour for DirectOnly<T> {
    type ConnectionHandler =
        Either<<T as NetworkBehaviour>::ConnectionHandler, dummy::ConnectionHandler>;
    type ToSwarm = <T as NetworkBehaviour>::ToSwarm;

    fn handle_pending_inbound_connection(
        &mut self,
        connection_id: ConnectionId,
        local_addr: &Multiaddr,
        remote_addr: &Multiaddr,
    ) -> Result<(), ConnectionDenied> {
        self.inner
            .handle_pending_inbound_connection(connection_id, local_addr, remote_addr)
    }

    fn handle_established_inbound_connection(
        &mut self,
        connection_id: ConnectionId,
        peer: PeerId,
        local_addr: &Multiaddr,
        remote_addr: &Multiaddr,
    ) -> Result<Self::ConnectionHandler, ConnectionDenied> {
        // For inbound (listener) connections the circuit shows up in local_addr.
        if addr_is_relayed(local_addr) {
            debug!(%peer, "DirectOnly: dummy handler for relayed inbound connection");
            self.dummy_connections.insert(connection_id, peer);
            return Ok(Either::Right(dummy::ConnectionHandler));
        }
        self.inner
            .handle_established_inbound_connection(connection_id, peer, local_addr, remote_addr)
            .map(Either::Left)
    }

    fn handle_pending_outbound_connection(
        &mut self,
        connection_id: ConnectionId,
        maybe_peer: Option<PeerId>,
        addresses: &[Multiaddr],
        effective_role: Endpoint,
    ) -> Result<Vec<Multiaddr>, ConnectionDenied> {
        self.inner.handle_pending_outbound_connection(
            connection_id,
            maybe_peer,
            addresses,
            effective_role,
        )
    }

    fn handle_established_outbound_connection(
        &mut self,
        connection_id: ConnectionId,
        peer: PeerId,
        addr: &Multiaddr,
        role_override: Endpoint,
        port_use: PortUse,
    ) -> Result<Self::ConnectionHandler, ConnectionDenied> {
        // For outbound (dialer) connections the circuit shows up in the dialed addr.
        if addr_is_relayed(addr) {
            debug!(%peer, "DirectOnly: dummy handler for relayed outbound connection");
            self.dummy_connections.insert(connection_id, peer);
            return Ok(Either::Right(dummy::ConnectionHandler));
        }
        self.inner
            .handle_established_outbound_connection(
                connection_id,
                peer,
                addr,
                role_override,
                port_use,
            )
            .map(Either::Left)
    }

    fn on_swarm_event(&mut self, event: FromSwarm) {
        match event {
            FromSwarm::ConnectionEstablished(e) => {
                if self.dummy_connections.contains_key(&e.connection_id) {
                    return;
                }
                self.inner.on_swarm_event(FromSwarm::ConnectionEstablished(
                    ConnectionEstablished {
                        other_established: e
                            .other_established
                            .saturating_sub(self.open_dummy_connections_to(e.peer_id)),
                        ..e
                    },
                ));
            }
            FromSwarm::ConnectionClosed(e) => {
                // `ConnectionClosed` is the last event for a connection id; forget it
                // here so the map doesn't grow unboundedly over the process lifetime.
                if self.dummy_connections.remove(&e.connection_id).is_some() {
                    return;
                }
                self.inner
                    .on_swarm_event(FromSwarm::ConnectionClosed(ConnectionClosed {
                        remaining_established: e
                            .remaining_established
                            .saturating_sub(self.open_dummy_connections_to(e.peer_id)),
                        ..e
                    }));
            }
            FromSwarm::AddressChange(e)
                if self.dummy_connections.contains_key(&e.connection_id) => {}
            // Listener and external-address events aren't tied to a single
            // connection and are always forwarded.
            other => self.inner.on_swarm_event(other),
        }
    }

    fn on_connection_handler_event(
        &mut self,
        peer_id: PeerId,
        connection_id: ConnectionId,
        event: THandlerOutEvent<Self>,
    ) {
        match event {
            Either::Left(event) => {
                self.inner
                    .on_connection_handler_event(peer_id, connection_id, event)
            }
            Either::Right(infallible) => match infallible {},
        }
    }

    fn poll(
        &mut self,
        cx: &mut Context<'_>,
    ) -> Poll<ToSwarm<Self::ToSwarm, THandlerInEvent<Self>>> {
        self.inner.poll(cx).map(|event| event.map_in(Either::Left))
    }
}

#[cfg(test)]
mod tests {
    use std::convert::Infallible;

    use libp2p::core::ConnectedPoint;

    use super::*;

    /// Minimal [`NetworkBehaviour`] that just records what it was told about
    /// via `on_swarm_event` — connection id plus the `other_established` /
    /// `remaining_established` count — so tests can assert on what `DirectOnly`
    /// forwards to `inner`.
    #[derive(Default)]
    struct Probe {
        established: Vec<(ConnectionId, usize)>,
        closed: Vec<(ConnectionId, usize)>,
    }

    impl NetworkBehaviour for Probe {
        type ConnectionHandler = dummy::ConnectionHandler;
        type ToSwarm = Infallible;

        fn handle_pending_inbound_connection(
            &mut self,
            _connection_id: ConnectionId,
            _local_addr: &Multiaddr,
            _remote_addr: &Multiaddr,
        ) -> Result<(), ConnectionDenied> {
            Ok(())
        }

        fn handle_established_inbound_connection(
            &mut self,
            _connection_id: ConnectionId,
            _peer: PeerId,
            _local_addr: &Multiaddr,
            _remote_addr: &Multiaddr,
        ) -> Result<Self::ConnectionHandler, ConnectionDenied> {
            Ok(dummy::ConnectionHandler)
        }

        fn handle_pending_outbound_connection(
            &mut self,
            _connection_id: ConnectionId,
            _maybe_peer: Option<PeerId>,
            _addresses: &[Multiaddr],
            _effective_role: Endpoint,
        ) -> Result<Vec<Multiaddr>, ConnectionDenied> {
            Ok(Vec::new())
        }

        fn handle_established_outbound_connection(
            &mut self,
            _connection_id: ConnectionId,
            _peer: PeerId,
            _addr: &Multiaddr,
            _role_override: Endpoint,
            _port_use: PortUse,
        ) -> Result<Self::ConnectionHandler, ConnectionDenied> {
            Ok(dummy::ConnectionHandler)
        }

        fn on_swarm_event(&mut self, event: FromSwarm) {
            match event {
                FromSwarm::ConnectionEstablished(e) => self
                    .established
                    .push((e.connection_id, e.other_established)),
                FromSwarm::ConnectionClosed(e) => {
                    self.closed.push((e.connection_id, e.remaining_established))
                }
                _ => {}
            }
        }

        fn on_connection_handler_event(
            &mut self,
            _peer_id: PeerId,
            _connection_id: ConnectionId,
            event: THandlerOutEvent<Self>,
        ) {
            match event {}
        }

        fn poll(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<ToSwarm<Self::ToSwarm, THandlerInEvent<Self>>> {
            Poll::Pending
        }
    }

    fn relayed_point() -> ConnectedPoint {
        ConnectedPoint::Listener {
            local_addr: "/ip4/1.2.3.4/tcp/7766"
                .parse::<Multiaddr>()
                .unwrap()
                .with(Protocol::P2p(PeerId::random()))
                .with(Protocol::P2pCircuit)
                .with(Protocol::P2p(PeerId::random())),
            send_back_addr: "/ip4/5.6.7.8/tcp/1".parse().unwrap(),
        }
    }

    fn direct_point() -> ConnectedPoint {
        ConnectedPoint::Listener {
            local_addr: "/ip4/1.2.3.4/tcp/7766".parse().unwrap(),
            send_back_addr: "/ip4/5.6.7.8/tcp/1".parse().unwrap(),
        }
    }

    /// `request_response::Behaviour` only records a connection in its bookkeeping
    /// via `handle_established_*_connection` (which `DirectOnly` skips for relayed
    /// connections), but asserts on a matching `ConnectionEstablished`/
    /// `ConnectionClosed` pair delivered through `on_swarm_event`. Forwarding
    /// those events unconditionally panics with "Expected some established
    /// connection to peer before closing."
    #[test]
    fn withholds_established_and_closed_events_for_relayed_connections() {
        let mut behaviour = DirectOnly::new(Probe::default());
        let peer = PeerId::random();
        let connection_id = ConnectionId::new_unchecked(0);
        let local_addr = "/ip4/1.2.3.4/tcp/7766"
            .parse::<Multiaddr>()
            .unwrap()
            .with(Protocol::P2p(PeerId::random()))
            .with(Protocol::P2pCircuit)
            .with(Protocol::P2p(PeerId::random()));
        let remote_addr: Multiaddr = "/ip4/5.6.7.8/tcp/1".parse().unwrap();

        let handler = behaviour
            .handle_established_inbound_connection(connection_id, peer, &local_addr, &remote_addr)
            .unwrap();
        assert!(matches!(handler, Either::Right(_)));

        let endpoint = relayed_point();
        behaviour.on_swarm_event(FromSwarm::ConnectionEstablished(
            libp2p::swarm::behaviour::ConnectionEstablished {
                peer_id: peer,
                connection_id,
                endpoint: &endpoint,
                failed_addresses: &[],
                other_established: 0,
            },
        ));
        behaviour.on_swarm_event(FromSwarm::ConnectionClosed(
            libp2p::swarm::behaviour::ConnectionClosed {
                peer_id: peer,
                connection_id,
                endpoint: &endpoint,
                cause: None,
                remaining_established: 0,
            },
        ));

        assert!(behaviour.inner_mut().established.is_empty());
        assert!(behaviour.inner_mut().closed.is_empty());
    }

    #[test]
    fn forwards_established_and_closed_events_for_direct_connections() {
        let mut behaviour = DirectOnly::new(Probe::default());
        let peer = PeerId::random();
        let connection_id = ConnectionId::new_unchecked(0);
        let local_addr: Multiaddr = "/ip4/1.2.3.4/tcp/7766".parse().unwrap();
        let remote_addr: Multiaddr = "/ip4/5.6.7.8/tcp/1".parse().unwrap();

        let handler = behaviour
            .handle_established_inbound_connection(connection_id, peer, &local_addr, &remote_addr)
            .unwrap();
        assert!(matches!(handler, Either::Left(_)));

        let endpoint = direct_point();
        behaviour.on_swarm_event(FromSwarm::ConnectionEstablished(
            libp2p::swarm::behaviour::ConnectionEstablished {
                peer_id: peer,
                connection_id,
                endpoint: &endpoint,
                failed_addresses: &[],
                other_established: 0,
            },
        ));
        behaviour.on_swarm_event(FromSwarm::ConnectionClosed(
            libp2p::swarm::behaviour::ConnectionClosed {
                peer_id: peer,
                connection_id,
                endpoint: &endpoint,
                cause: None,
                remaining_established: 0,
            },
        ));

        assert_eq!(behaviour.inner_mut().established, vec![(connection_id, 0)]);
        assert_eq!(behaviour.inner_mut().closed, vec![(connection_id, 0)]);
    }

    /// The swarm counts relayed connections in `other_established` /
    /// `remaining_established` even though `DirectOnly` hides them from `inner`.
    /// Forwarded unadjusted, `inner` would treat the first direct connection as
    /// a reconnect (gossipsub then never sends its subscription handshake) and
    /// a direct disconnect as leaving connections behind (skipping full peer
    /// cleanup, tripping request-response's debug_assert). The counts must be
    /// reduced by the hidden open dummy connections to that peer.
    #[test]
    fn adjusts_connection_counts_for_hidden_relayed_connections() {
        let mut behaviour = DirectOnly::new(Probe::default());
        let peer = PeerId::random();
        let relayed_id = ConnectionId::new_unchecked(0);
        let direct_id = ConnectionId::new_unchecked(1);
        let relayed_local_addr = "/ip4/1.2.3.4/tcp/7766"
            .parse::<Multiaddr>()
            .unwrap()
            .with(Protocol::P2p(PeerId::random()))
            .with(Protocol::P2pCircuit)
            .with(Protocol::P2p(PeerId::random()));
        let direct_local_addr: Multiaddr = "/ip4/1.2.3.4/tcp/7766".parse().unwrap();
        let remote_addr: Multiaddr = "/ip4/5.6.7.8/tcp/1".parse().unwrap();

        // Relayed connection first: dummy handler, events withheld.
        behaviour
            .handle_established_inbound_connection(
                relayed_id,
                peer,
                &relayed_local_addr,
                &remote_addr,
            )
            .unwrap();
        let relayed_endpoint = relayed_point();
        behaviour.on_swarm_event(FromSwarm::ConnectionEstablished(
            libp2p::swarm::behaviour::ConnectionEstablished {
                peer_id: peer,
                connection_id: relayed_id,
                endpoint: &relayed_endpoint,
                failed_addresses: &[],
                other_established: 0,
            },
        ));

        // Direct connection second: the swarm reports `other_established = 1`
        // (the relayed connection), but `inner` must see its first connection.
        behaviour
            .handle_established_inbound_connection(
                direct_id,
                peer,
                &direct_local_addr,
                &remote_addr,
            )
            .unwrap();
        let direct_endpoint = direct_point();
        behaviour.on_swarm_event(FromSwarm::ConnectionEstablished(
            libp2p::swarm::behaviour::ConnectionEstablished {
                peer_id: peer,
                connection_id: direct_id,
                endpoint: &direct_endpoint,
                failed_addresses: &[],
                other_established: 1,
            },
        ));
        assert_eq!(behaviour.inner_mut().established, vec![(direct_id, 0)]);

        // Direct connection closes while the circuit is still open: the swarm
        // reports `remaining_established = 1`, but for `inner` no connections
        // remain.
        behaviour.on_swarm_event(FromSwarm::ConnectionClosed(
            libp2p::swarm::behaviour::ConnectionClosed {
                peer_id: peer,
                connection_id: direct_id,
                endpoint: &direct_endpoint,
                cause: None,
                remaining_established: 1,
            },
        ));
        assert_eq!(behaviour.inner_mut().closed, vec![(direct_id, 0)]);

        // Circuit closes last: withheld from `inner` and forgotten.
        behaviour.on_swarm_event(FromSwarm::ConnectionClosed(
            libp2p::swarm::behaviour::ConnectionClosed {
                peer_id: peer,
                connection_id: relayed_id,
                endpoint: &relayed_endpoint,
                cause: None,
                remaining_established: 0,
            },
        ));
        assert_eq!(behaviour.inner_mut().closed, vec![(direct_id, 0)]);
        assert!(behaviour.dummy_connections.is_empty());
    }

    #[test]
    fn detects_relayed_circuit_address() {
        // /ip4/1.2.3.4/tcp/7766/p2p/<relay>/p2p-circuit/p2p/<target>
        let relayed = "/ip4/1.2.3.4/tcp/7766"
            .parse::<Multiaddr>()
            .unwrap()
            .with(Protocol::P2p(PeerId::random()))
            .with(Protocol::P2pCircuit)
            .with(Protocol::P2p(PeerId::random()));
        assert!(addr_is_relayed(&relayed));
    }

    #[test]
    fn direct_tcp_address_is_not_relayed() {
        let direct: Multiaddr = "/ip4/1.2.3.4/tcp/7766"
            .parse::<Multiaddr>()
            .unwrap()
            .with(Protocol::P2p(PeerId::random()));
        assert!(!addr_is_relayed(&direct));
    }

    #[test]
    fn direct_quic_address_is_not_relayed() {
        let direct: Multiaddr = "/ip4/1.2.3.4/udp/7766/quic-v1".parse().unwrap();
        assert!(!addr_is_relayed(&direct));
    }
}
