title = "Server Configuration"

[General]
Host = "localhost"
Port = 7766
Password = "1234"
Debug = true

[Rooms]

[Rooms.General]
Name = "General"
SaveFile = "General_playlist.toml"

[Rooms.Test]
Name = "Test"
SaveFile = "Test_playlist.toml"
