title = "Server Configuration"

[General]
Host = "0.0.0.0"
Port = 7766
DBPath = ".db/"
Debug = true
# Cert = "cert.pem"
# Key = "key.pem"
# Password = "1234"
# DbUpdateInterval = 2
# DbWaitTimeout = 4
# DbStatInterval = 120


[Rooms]
[Rooms.General]
persistent = false

[Rooms.Test]
persistent = false
