title = "Server Configuration"

[General]
Host = "0.0.0.0"
Port = 7766
# Cert = "cert.pem"
# Key = "key.pem"
# Password = "1234"
Debug = false

[Rooms]
[Rooms.General]
SaveFile = "General_playlist.toml"

[Rooms.Test]
SaveFile = "Test_playlist.toml"
