title = "Server Configuration"

[General]
Host = "0.0.0.0"
Port = 7766
Password = "1234"
Debug = true

[Rooms]

[Rooms.General]
SaveFile = "General_playlist.toml"

[Rooms.Test]
SaveFile = "Test_playlist.toml"
