[package]
name = "niketsu-core"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
url.workspace = true
enum_dispatch.workspace = true
arc-swap.workspace = true
arcstr.workspace = true
im.workspace = true
once_cell.workspace = true
directories = "5.0"
serde_with = "3.0"
rayon = "1.7"
fuzzy-matcher = "0.3"
itertools = "0.11"
futures = "0.3"
num-traits = "0.2"
chrono = "0.4"
whoami = "1.4"
async-trait = "0.1"
toml = "0.8"
typed-builder = "0.16"
fake = "2.8"
ordered-float = "4"

[dev-dependencies]
tempfile = "3.6"
mockall = "0.11"
