name: Github Pages

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/book.yaml'
      - 'book/**'
      - 'flake.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build site
        working-directory: ./book
        run: nix develop --command mdbook build
      - name: Setup Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          path: book/book
      - name: Deploy to GitHub Pages
        id: deployment
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/deploy-pages@v4
