name: Build Action

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix: 
        target: 
          - aarch64-linux
          - x86_64-linux
        package:
          - niketsu-client
          - niketsu-server
        include:
          # Windows build from x86_64-linux
          - target: x86_64-linux
            package: niketsu-client-windows
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = aarch64-linux i686-linux
      - uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - uses: cachix/cachix-action@v12
        with:
          name: niketsu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run build
        run: nix build .#packages.${{ matrix.target }}.${{ matrix.package }}
      - name: Rename
        if: ${{ matrix.package == 'niketsu-client-windows' }}
        run: mkdir out && cp result out/x86_64-windows-niketsu-client.zip
      - name: Rename
        if: ${{ matrix.package != 'niketsu-client-windows' }}
        run: mkdir out && cp result/bin/niketsu* out/${{ matrix.target }}-${{ matrix.package }}
      - name: Pre-Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'push' }}
        with:
          prerelease: true
          tag_name: nightly
          files: out/*
