name: Build Action

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix: 
        target: 
          - aarch64-linux
          - x86_64-linux
        package:
          - niketsu-client
          - niketsu-server
        isMain:
          - ${{ contains(github.ref, 'main') }}
        exclude:
          - target: aarch64-linux
            package: niketsu-client
            isMain: false
        include:
          # Windows build from x86_64-linux
          - target: x86_64-linux
            package: niketsu-client-windows
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            extra-platforms = aarch64-linux i686-linux
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Run build
        run: nix build .#packages.${{ matrix.target }}.${{ matrix.package }}
      - name: Rename
        if: ${{ matrix.package == 'niketsu-client-windows' }}
        run: mkdir out && cp result out/x86_64-windows-niketsu-client.zip
      - name: Rename
        if: ${{ matrix.package != 'niketsu-client-windows' }}
        run: mkdir out && cp result/bin/niketsu* out/${{ matrix.target }}-${{ matrix.package }}
      - name: Pre-Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'push' && matrix.package != 'niketsu-client' }}
        with:
          prerelease: true
          tag_name: nightly
          files: out/*
