name: Check Actions

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: Check Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: niketsu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run Checks
        run: nix flake check --fallback

  format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: niketsu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run verify commands
        run: nix develop --fallback --command treefmt --fail-on-change

  test:
    name: Check Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: niketsu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run verify commands
        run: nix develop --fallback --command nextest run

