name: Coverage

on:
  push:
    branches: [main]

jobs:
  rust-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Coverage
        run: nix develop --command tarpaulin --out lcov --output-dir ./coverage
      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v1
