name: Deploy Server Image to GHCR

on:
  push:
    paths:
      - '.github/workflows/docker.yml'
      - 'Dockerfile'
      - 'server/**'
      - 'go.*'
    branches: [main]
    tags: 
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: niketsu-server

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
      - name: Format tags and labels
        id: format
        run: |
          export TAGS=$(echo "${{ steps.meta.outputs.tags }}" | cut -d':' -f2 | tr '\n' ',' | tr -d ' ' | sed 's/,$//')
          echo "tags=$TAGS " >> $GITHUB_OUTPUT
          export LABELS=$(echo "${{ steps.meta.outputs.labels }}" | tr '\n' ',' | tr -d ' ' | sed 's/,$//')
          echo "labels=$LABELS " >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6.2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.format.outputs.tags }}
          labels: ${{ steps.format.outputs.labels }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}