name: Nix Related Actions

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: Nix Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Checks
        run: nix flake check

  format:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run verify commands
        run: nix develop --command treefmt --fail-on-change