name: Nightly Tag

on:
  push:
    branches: [main]

jobs:
  checks:
    name: Move nightly tag to latest commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        with:
          ref: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
